--- 
driver: 
  name: vagrant
platforms: 
  - 
    driver_config: 
      network: 
        - 
          - private_network
          - 
            ip: "33.33.33.10"
    name: ubuntu-12.04
provisioner: 
  name: chef_solo

suites: 
  - 
    attributes: 
      mysql: 
        server_debian_password: debpass
        server_repl_password: replpass
        server_root_password: rootpass
    name: default
    run_list: 
      - "kitchen_mysql::default"
